/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author zaidan
 */
import javax.swing.*;
import java.util.*;

public class Proyek2 extends javax.swing.JFrame {
    // Atribut
    DefaultListModel<String> dlm;
    List<String> lItems = new ArrayList<>();
    Set<String> sItems = new LinkedHashSet<>();
    Map<Integer, String> mItems = new LinkedHashMap<>();
    
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu jati", "tikus", "meja", "buku tulis", "tas"};
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Proyek2.class.getName());
    
    public Proyek2() {
        initComponents();
        dlm = new DefaultListModel<>();
        jListItem.setModel(dlm);
        
        for (String data : datas){
            dlm.addElement(data);
            updateJumDataTersimpan();
        }
    }
    
    private void updateJumDataTersimpan(){
        jLabelJumlahList.setText(
            "Data List tersimpan = " + lItems.size());
        jLabelJumlahSet.setText(
            "Data Set tersimpan = " + sItems.size());
        jLabelJumlahDataMap.setText(
            "Data Map tersimpan = " + mItems.size());
    }
    
    private void addItem(String namaItem){
        dlm.addElement(namaItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldItem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jInsertDataList = new javax.swing.JButton();
        jadd = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jClearAll = new javax.swing.JButton();
        jLabelJumlahList = new javax.swing.JLabel();
        jSaveDataList = new javax.swing.JButton();
        InsertMap = new javax.swing.JButton();
        saveToSet = new javax.swing.JButton();
        insertSet = new javax.swing.JButton();
        saveMap = new javax.swing.JButton();
        jLabelJumlahSet = new javax.swing.JLabel();
        jLabelJumlahDataMap = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jLabel1.setText("Item name:");

        jInsertDataList.setText("<- insert data List");
        jInsertDataList.addActionListener(this::jInsertDataListActionPerformed);

        jadd.setText("add");
        jadd.addActionListener(this::jaddActionPerformed);

        jdelete.setText("delete");
        jdelete.addActionListener(this::jdeleteActionPerformed);

        jupdate.setText("update");
        jupdate.addActionListener(this::jupdateActionPerformed);

        jClearAll.setText("clear all");
        jClearAll.addActionListener(this::jClearAllActionPerformed);

        jLabelJumlahList.setText("Data tersimpan = 0");

        jSaveDataList.setText("save to List ->");
        jSaveDataList.addActionListener(this::jSaveDataListActionPerformed);

        InsertMap.setText("<- insert data Map");
        InsertMap.addActionListener(this::InsertMapActionPerformed);

        saveToSet.setText("save to Set ->");
        saveToSet.addActionListener(this::saveToSetActionPerformed);

        insertSet.setText("<- insert data Set");
        insertSet.addActionListener(this::insertSetActionPerformed);

        saveMap.setText("save to Map ->");
        saveMap.addActionListener(this::saveMapActionPerformed);

        jLabelJumlahSet.setText("Data tersimpan = 0");

        jLabelJumlahDataMap.setText("Data tersimpan = 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jadd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jInsertDataList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveToSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSaveDataList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJumlahList)
                            .addComponent(jLabelJumlahSet)
                            .addComponent(jLabelJumlahDataMap))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJumlahList)
                            .addComponent(jSaveDataList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveToSet)
                            .addComponent(jLabelJumlahSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insertSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveMap)
                            .addComponent(jLabelJumlahDataMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InsertMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearAll)
                    .addComponent(jupdate)
                    .addComponent(jadd)
                    .addComponent(jdelete))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataListActionPerformed
        // Insert Data
        
        for (String item : lItems){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertDataListActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        // Delete
        int index = jListItem.getSelectedIndex();

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus.");
            return;
        }

        dlm.removeElementAt(index);
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        // add
        String item = jTextFieldItem.getText().trim();

        if (item.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama item tidak boleh kosong.");
            return;
        }

        addItem(item);
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jaddActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // Update
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldItem.getText().trim();

        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah.");
            return;
        }

        if (selected.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama item tidak boleh kosong.");
            return;
        }

        dlm.setElementAt(selected, index);
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jupdateActionPerformed

    private void jClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllActionPerformed
        // clear
        dlm.clear();
        lItems.clear();
        sItems.clear();
        mItems.clear();

        updateJumDataTersimpan();
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jClearAllActionPerformed

    private void jSaveDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveDataListActionPerformed
        // save data List
        if(!lItems.isEmpty()){
            lItems.clear();
        }
        
        for(int i = 0; i < dlm.getSize(); i++){
            lItems.add(dlm.getElementAt(i));
        }
        
        updateJumDataTersimpan();
    }//GEN-LAST:event_jSaveDataListActionPerformed

    private void saveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToSetActionPerformed
        // save data Set

        for (int i = 0; i < dlm.getSize(); i++) {
            sItems.add(dlm.getElementAt(i));
        }

        updateJumDataTersimpan();
    }//GEN-LAST:event_saveToSetActionPerformed

    private void saveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMapActionPerformed
        // save data Map

        for (int i = 0; i < dlm.getSize(); i++) {
            mItems.put(i, dlm.getElementAt(i));
        }

        updateJumDataTersimpan();
    }//GEN-LAST:event_saveMapActionPerformed

    private void insertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertSetActionPerformed
        // insert Set
        
        for(String item : sItems){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_insertSetActionPerformed

    private void InsertMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertMapActionPerformed
        // insert Map
        
        for (Map.Entry<Integer,String> item : mItems.entrySet()){
            dlm.addElement(item.getValue());
        }
    }//GEN-LAST:event_InsertMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Proyek2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertMap;
    private javax.swing.JButton insertSet;
    private javax.swing.JButton jClearAll;
    private javax.swing.JButton jInsertDataList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelJumlahDataMap;
    private javax.swing.JLabel jLabelJumlahList;
    private javax.swing.JLabel jLabelJumlahSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JButton jSaveDataList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jupdate;
    private javax.swing.JButton saveMap;
    private javax.swing.JButton saveToSet;
    // End of variables declaration//GEN-END:variables
}
